import { resolve } from '@orioro/resolve'

export const BASE_MAP_LAYERS_Z_INDEX_BASE = 100

export function baseMapSources({ GLOBAL_CONTEXT }) {
  return {
    maptiler_planet: {
      type: 'vector',
      tiles: [
        `https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?key=${GLOBAL_CONTEXT.MAP_TILER_API_KEY}`,
      ],
    },
  }
}

export function baseMapLayers({ GLOBAL_CONTEXT }) {
  return {
    Landcover: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 1,

        id: 'Landcover',
        type: 'fill',
        source: 'maptiler_planet',
        'source-layer': 'landcover',
        layout: {
          visibility: 'visible',
        },
        interactive: false,
        paint: {
          'fill-antialias': false,
          'fill-color': 'hsl(96, 44%, 79%)',
          // "fill-color": "red",
          'fill-opacity': 0.6,
          // "fill-opacity": {
          //   "stops": [
          //     [8, 0.2],
          //     [9, 0.25],
          //     [11, 0.35]
          //   ]
          // }
        },
        filter: ['in', 'class', 'wood', 'grass'],
      }),
    ),
    Forest: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 2,

        id: 'Forest',
        type: 'fill',
        source: 'maptiler_planet',
        'source-layer': 'globallandcover',
        maxzoom: 7,
        layout: {
          visibility: 'visible',
        },
        interactive: false,
        paint: {
          // "fill-color": "hsla(96, 44%, 79%, 0.15)"
          'fill-color': 'hsl(96, 44%, 79%)',
        },
        filter: ['in', 'class', 'forest', 'tree'],
      }),
    ),
    Road_Network: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 3,

        id: 'Road_Network',
        type: 'line',
        source: 'maptiler_planet',
        'source-layer': 'transportation',
        minzoom: 6,
        layout: {
          'line-cap': 'butt',
          'line-join': 'round',
          visibility: 'visible',
        },
        paint: {
          'line-color': 'hsl(0, 0%, 100%)',
          'line-width': [
            'interpolate',
            ['linear', 2],
            ['zoom'],
            5,
            0.5,
            6,
            [
              'match',
              ['get', 'class'],
              ['motorway'],
              ['match', ['get', 'brunnel'], ['bridge'], 0, 1],
              ['trunk', 'primary'],
              0,
              0,
            ],
            10,
            [
              'match',
              ['get', 'class'],
              ['motorway'],
              ['match', ['get', 'ramp'], 1, 0, 2.5],
              ['trunk', 'primary'],
              1.5,
              1,
            ],
            12,
            [
              'match',
              ['get', 'class'],
              ['motorway'],
              ['match', ['get', 'ramp'], 1, 1, 4],
              ['trunk'],
              2.5,
              ['primary'],
              2.5,
              ['secondary', 'tertiary'],
              1.5,
              ['minor', 'service', 'track'],
              0,
              1,
            ],
            14,
            [
              'match',
              ['get', 'class'],
              ['motorway'],
              ['match', ['get', 'ramp'], 1, 5, 6],
              ['trunk'],
              3,
              ['primary'],
              5,
              ['secondary'],
              4,
              ['tertiary'],
              3,
              ['minor', 'service', 'track'],
              2,
              2,
            ],
            16,
            [
              'match',
              ['get', 'class'],
              ['motorway', 'trunk', 'primary'],
              8,
              ['secondary'],
              7,
              ['tertiary'],
              6,
              ['minor', 'service', 'track'],
              4,
              4,
            ],
            20,
            [
              'match',
              ['get', 'class'],
              ['motorway', 'trunk', 'primary'],
              24,
              ['secondary'],
              24,
              ['tertiary'],
              24,
              ['minor', 'service', 'track'],
              16,
              16,
            ],
          ],
        },
        metadata: {},
        filter: [
          'all',
          ['!=', 'brunnel', 'tunnel'],
          [
            '!in',
            'class',
            'ferry',
            'rail',
            'transit',
            'pier',
            'bridge',
            'path',
            'aerialway',
            'motorway_construction',
            'trunk_construction',
            'primary_construction',
            'secondary_construction',
            'tertiary_construction',
            'minor_construction',
            'service_construction',
            'track_construction',
          ],
        ],
      }),
    ),
    Road_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 4,

        id: 'Road labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'transportation_name',
        minzoom: 14,
        layout: {
          'symbol-avoid-edges': false,
          'symbol-placement': 'line',
          'symbol-spacing': {
            stops: [
              [6, 200],
              [16, 250],
              [20, 250],
              [22, 600],
            ],
          },
          'text-field': ['coalesce', ['get', 'name:en'], ['get', 'name']],
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-justify': 'center',
          'text-letter-spacing': [
            'interpolate',
            ['linear', 1],
            ['zoom'],
            13,
            0,
            16,
            ['match', ['get', 'class'], 'primary', 0.2, 0.1],
          ],
          'text-pitch-alignment': 'auto',
          'text-rotation-alignment': 'auto',
          'text-size': [
            'interpolate',
            ['linear'],
            ['zoom'],
            14,
            ['match', ['get', 'class'], ['primary'], 10, 7],
            15,
            [
              'match',
              ['get', 'class'],
              ['primary'],
              10,
              ['secondary', 'tertiary'],
              9,
              7,
            ],
            16,
            [
              'match',
              ['get', 'class'],
              ['primary', 'secondary', 'tertiary'],
              11,
              10,
            ],
            18,
            [
              'match',
              ['get', 'class'],
              ['primary', 'secondary', 'tertiary'],
              13,
              12,
            ],
          ],
          visibility: 'visible',
        },
        paint: {
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(0,0%,100%)',
          'text-halo-width': 1.5,
          'text-opacity': [
            'step',
            ['zoom'],
            1,
            14,
            ['match', ['get', 'class'], ['primary'], 1, 0],
            15,
            [
              'match',
              ['get', 'class'],
              ['primary', 'secondary', 'tertiary'],
              1,
              0,
            ],
            16,
            1,
          ],
        },
        filter: [
          'in',
          'class',
          'primary',
          'secondary',
          'tertiary',
          'minor',
          'service',
        ],
      }),
    ),
    Place_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 5,

        id: 'Place_labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'place',
        minzoom: 13,
        layout: {
          'symbol-sort-key': ['to-number', ['get', 'rank']],
          'text-anchor': 'center',
          'text-field': '{name}',
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-keep-upright': true,
          'text-max-width': 10,
          'text-offset': [0.2, 0.2],
          'text-size': [
            'interpolate',
            ['linear', 1],
            ['zoom'],
            12,
            10,
            13,
            [
              'match',
              ['get', 'class'],
              ['suburb', 'neighborhood', 'neighbourhood'],
              12,
              11,
            ],
            14,
            [
              'match',
              ['get', 'class'],
              ['suburb', 'neighborhood', 'neighbourhood'],
              12,
              11,
            ],
            16,
            [
              'match',
              ['get', 'class'],
              ['suburb', 'neighborhood', 'neighbourhood'],
              14,
              13,
            ],
          ],
          'text-transform': 'none',
          visibility: 'visible',
        },
        paint: {
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(0, 0%, 100%)',
          'text-halo-width': 1.5,
          'text-opacity': [
            'step',
            ['zoom'],
            0,
            13,
            [
              'match',
              ['get', 'class'],
              ['suburb', 'neighborhood', 'neighbourhood'],
              1,
              0,
            ],
            14,
            1,
          ],
        },
        filter: [
          '!in',
          'class',
          'city',
          'continent',
          'country',
          'province',
          'state',
          'town',
          'village',
          'place',
        ],
      }),
    ),

    Village_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 6,

        id: 'Village labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'place',
        minzoom: 12,
        layout: {
          'symbol-sort-key': ['to-number', ['get', 'rank']],
          'text-anchor': 'center',
          'text-field': '{name}',
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-keep-upright': true,
          'text-max-width': 10,
          'text-offset': [0.2, 0.2],
          'text-size': [
            'interpolate',
            ['linear', 1],
            ['zoom'],
            12,
            10,
            13,
            12,
            14,
            14,
            16,
            13,
          ],
          'text-transform': 'none',
          visibility: 'visible',
        },
        paint: {
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(0, 0%, 100%)',
          'text-halo-width': 1.5,
          'text-opacity': 1,
        },
        filter: ['==', 'class', 'village'],
      }),
    ),
    Town_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 7,
        id: 'Town labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'place',
        minzoom: 11,
        maxzoom: 16,
        layout: {
          'symbol-sort-key': ['to-number', ['get', 'rank']],
          'text-anchor': 'center',
          'text-field': ['get', 'name'],
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-keep-upright': true,
          'text-max-width': 10,
          'text-offset': [0.2, 0.2],
          'text-size': [
            'interpolate',
            ['linear'],
            ['zoom'],
            10,
            11,
            13,
            14,
            14,
            15,
          ],
          'text-transform': 'none',
          visibility: 'visible',
        },
        paint: {
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(0,0%,100%)',
          'text-halo-width': 1.5,
        },
        filter: ['==', 'class', 'town'],
      }),
    ),
    State_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 7,


        id: 'State labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'place',
        minzoom: 5,
        maxzoom: 8,
        layout: {
          'symbol-sort-key': ['to-number', ['get', 'rank']],
          'text-allow-overlap': false,
          'text-field': ['get', 'name'],
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-max-width': 9,
          'text-size': [
            'interpolate',
            ['linear', 1],
            ['zoom'],
            5,
            ['match', ['get', 'rank'], 1, 10, 10],
            11,
            ['match', ['get', 'rank'], 1, 16, 16],
          ],
          'text-transform': 'uppercase',
          visibility: 'visible',
        },
        paint: {
          'icon-opacity': 0.75,
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(30,25%,98%)',
          'text-halo-width': 1.5,
          'text-opacity': 0.75,
        },
        filter: ['all', ['==', 'class', 'state'], ['==', 'rank', 1]],
      }),
    ),
    City_labels: resolve.fn(({ app }) =>
      resolve.literal({
        hidden: app?.baseMapStyle === 'satellite',
        zIndex: BASE_MAP_LAYERS_Z_INDEX_BASE + 7,

        id: 'City labels',
        type: 'symbol',
        source: 'maptiler_planet',
        'source-layer': 'place',
        minzoom: 5,
        maxzoom: 14,
        layout: {
          'symbol-sort-key': ['to-number', ['get', 'rank']],
          'text-anchor': 'center',
          'text-field': '{name:en}',
          'text-font': ['Metropolis Semi Bold', 'Noto Sans Bold'],
          'text-keep-upright': false,
          'text-max-width': 10,
          'text-offset': [0.2, 0.2],
          'text-size': [
            'interpolate',
            ['linear', 1],
            ['zoom'],
            5,
            ['case', ['\u003E=', ['get', 'rank'], 6], 11, 12],
            9,
            ['case', ['\u003E=', ['get', 'rank'], 6], 12, 14],
            13,
            ['case', ['\u003E=', ['get', 'rank'], 6], 16, 18],
            14,
            ['case', ['\u003E=', ['get', 'rank'], 6], 20, 22],
          ],
          'text-transform': 'none',
          visibility: 'visible',
        },
        paint: {
          'text-color': 'hsl(204, 11%, 47%)',
          'text-halo-blur': 0,
          'text-halo-color': 'hsl(0,0%,100%)',
          'text-halo-width': 1.5,
        },
        filter: ['all', ['==', 'class', 'city'], ['has', 'rank']],
      }),
    ),
  }
}
