git filter-repo \
  --path .editorconfig \
  --path .gitattributes \
  --path .gitignore \
  --path .prettierrc \
  --path .yarnrc.yml \
  --path .package.json \
  --path README.md \
  --path packages/web-ui/components/GeoReDUS \
  --path packages/web-ui/components/InputProvider/Inputs/GeoFile \
  --path packages/react-maplibre-util
